%% Feature frequency versus score script

cd '/Users/Phillip/Documents/Research/Image Memorability/MATLAB code/Analysis/Prediction/version_2010_aug_8/'
load datamem     % load annotations, stats, and precomputed descriptors (this file is generated by the script memory.m)

load('/Users/Phillip/Documents/Research/Image Memorability/MATLAB code/Analysis/Feature analysis/object_expected_memorabilities.mat');
load('/Users/Phillip/Documents/Research/Image Memorability/MATLAB code/Analysis/Feature analysis/object_frequencies.mat');


%% build feature vector for each image
PlotFeatureFrequencyVersusScore2(frequencies,object_expected_memorabilities);

